# Generated by Django 3.0.3 on 2020-02-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0002_historicalcow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCow',
        ),
    ]
