# Generated by Django 3.0.3 on 2020-02-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0004_cow_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='history',
        ),
    ]
