# Generated by Django 3.0.3 on 2020-02-20 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0005_remove_cow_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
