# Generated by Django 3.0.3 on 2020-02-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0006_cow_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='cow_type',
            field=models.CharField(choices=[('-f satanic', '-f satanic'), ('-f ghostbusters', '-f ghostbusters'), ('-f sodomized', '-f sodomized'), ('-f dragon', '-f dragon')], default='', max_length=15),
        ),
    ]
