# Generated by Django 3.0.3 on 2020-02-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0007_cow_cow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='cow_type',
            field=models.CharField(choices=[('satanic', 'satanic'), ('ghostbusters', 'ghostbusters'), ('sodomized', 'sodomized'), ('dragon', 'dragon')], default='default', max_length=12),
        ),
    ]
