# Generated by Django 3.0.3 on 2020-02-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0008_auto_20200220_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_type', models.CharField(choices=[('satanic', 'satanic'), ('ghostbusters', 'ghostbusters'), ('sodomized', 'sodomized'), ('dragon', 'dragon')], default='default', max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='cow',
            name='cow_type',
        ),
    ]
