# Generated by Django 3.0.3 on 2020-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0009_auto_20200220_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cow_type',
        ),
        migrations.AddField(
            model_name='cow',
            name='cow_type',
            field=models.CharField(choices=[('satanic', 'satanic'), ('ghostbusters', 'ghostbusters'), ('sodomized', 'sodomized'), ('dragon', 'dragon')], default='default', max_length=12),
        ),
    ]
