# Generated by Django 3.0.3 on 2020-02-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0010_auto_20200220_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cow',
            old_name='cow_type',
            new_name='Cow_Type',
        ),
    ]
