# Generated by Django 3.0.3 on 2020-02-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0011_auto_20200220_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='text_input',
            field=models.CharField(max_length=30),
        ),
    ]
